name: Check Lint and TS

on:
  push:
    branches: 
      - '**'

jobs:
  lint-and-ts-check:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - uses: actions/setup-node@v3
      with:
        node-version: '16.16.0'
        
    - name: Install dependencies
    - run: npm ci
    - name: EsLint Check
    - run: npm run lint
    - name: TS Check
    - run: npm run ts
